### ISSUE TITLE
Render component with directive was rendered 2 times  

### ISSUE THREAD

**Issue by quangfabfitfun** [ngReact/ngReact#146] opened 2016-03-25 04:19 UTC
- When I use method render with directive which i created (eg. `<hello-component></hello-component>`) , I see the code render run two times on console. How can i solve this problem? here my code implement

`var HelloComponent = React.createClass({
  	propTypes: {
    	id : React.PropTypes.number.isRequired,
    	name : React.PropTypes.string.isRequired
  	},
  	render: function() {
      console.log('abc')
    	return <span>Hello {this.props.id} {this.props.name}</span>
  	}
});
app.directive('helloComponent', function(reactDirective) {
  return reactDirective(HelloComponent);
});
`

<img width="1680" alt="screen shot 2016-03-25 at 11 13 06 am" src="https://cloud.githubusercontent.com/assets/16550896/14037868/61156ef2-f27b-11e5-90bf-7ab379419a2e.png">

- everything's ok with `<react-component>`

**Comment by kasperp** [comment] 2016-04-16 14:32
@quangfabfitfun is this a duplicate of #114 ?

**Comment by kasperp** [comment] 2016-06-05 08:19
closed due to inactivity, feel free to reopen

**Closed by kasperp** 2016-06-05 08:19 UTC
