### ISSUE TITLE
Child data not being propagated to components

### ISSUE THREAD

**Issue by burtonsamograd-adsk** [ngReact/ngReact#167] opened 2016-09-14 18:00 UTC
We have a react class that wraps button that takes the label text as a child of the element, like this:

    <orn-button>Button</orn-button>

I am able to get the button to show up as intended, but the child contents are not picked up by the component.  I have also found this problem with another more complex control that I am testing as well.

Any ideas on why the children text and other elements are not being propagated to the React components I am trying to use?  It seems that the component can see the elements, or else the complex control would not build itself internally, but the data they contain is empty.

**Comment by kasperp** [comment] 2016-09-14 19:16
@burtonsamograd-adsk could you try to post some of the component code. That may help narrow down whats going on.

**Comment by burtonsamograd-adsk** [comment] 2016-09-14 19:30
I can't really do that as it's proprietary.  I was wondering if this might have been a known bug.

**Comment by kasperp** [comment] 2016-09-14 19:30
It is not a know bug, perhaps you can provide a small example that illustrates the issue

**Comment by burtonsamograd-adsk** [comment] 2016-09-14 19:56
The code is a typescript module.  The button's inner JSX is similar to the following:

    <label className="label--class">{this.props.children}</label>

When I inspect the button in Chrome, I can see the <orn-button> has changed into a nested <button>/<label>, so I know the react component is being used.  The only problem is that within the label there is no text, with the inner portion of the label being like the code above.

**Comment by kasperp** [comment] 2016-09-14 20:02
Does the component work outside of ngReact in a standalone React application ?

**Comment by burtonsamograd-adsk** [comment] 2016-09-14 20:08
Yes, it does.  We are using React Storybook for live testing of the components.

**Comment by kasperp** [comment] 2016-09-14 20:14
I'm sorry that I can't help you further, but it is kind of hard without a running example. 

If you look at the examples in the repository, e.g. http://ngreact.github.io/ngReact/examples/table/ code here https://github.com/ngReact/ngReact/blob/master/examples/table/app.js#L42. You can see that we render child components. 

Or I'm I missing the point ?

**Comment by burtonsamograd-adsk** [comment] 2016-09-14 20:48
Maybe, (re: missing the point :).  The examples do show that child components are rendered, but what I'm trying to do is see why the component's 'children'  (which are accessed through this.props.children in the component) aren't being rendered.

**Comment by kasperp** [comment] 2016-09-14 20:53
okay, so in your components render function you access this.props.children and get undefined ?

**Comment by burtonsamograd-adsk** [comment] 2016-09-14 21:10
Yes, the behaviour I'm seeing would point to this.props.children being undefined in the components.

**Comment by burtonsamograd-adsk** [comment] 2016-09-15 02:09
Here is an example that does not seem to be working for me:

`import * as React from 'react';

class Soe extends React.Component<any, any> {
  render(): JSX.Element {
    return (
        <span>
            {this.props.children}
        </span>
    );
  }
}

export default Soe;
`

After initializing with:

`
app.directive('soe', function(reactDirective) {
    return reactDirective(OrionReactUi.Soe);
});
`

When used like:

`<soe>This is a GitHub example</soe>`

When I inspect all I see is:

`
<soe><span data-reactroot=""></span></soe>
`

**Comment by burtonsamograd-adsk** [comment] 2016-09-15 16:40
Bump, in case the last post was not noticed.

**Comment by kasperp** [comment] 2016-09-16 05:37
Thanks for the example, I'll look into it.

**Comment by kasperp** [comment] 2016-09-16 19:25
@burtonsamograd-adsk sorry I didn't catch this earlier but this is a duplicate of #128. The short answer is that it isn't supported. See my answer for #128 for details about a work around.

**Closed by kasperp** 2016-09-16 19:25 UTC
